sudo: false
language: node_js
node_js:
- lts/*
cache:
  directories:
  - node_modules
before_script:
- npm install
- npm run build:current
script:
- npm run test:build
after_success:
- npm run typedoc
deploy:
- provider: heroku
  api_key: "$HEROKU_TOKEN"
  app:
    develop: crown-lab-backend-sandbox
    master: crown-lab-backend-dev
  on:
    repo: pixelmixr/crown-lab-backend
- provider: pages
  skip_cleanup: true
  local_dir: docs/
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: crown-lab-backend-*.tgz
  skip_cleanup: true
  on:
    tags: true
